package pojo;

// Generated 01-juin-2014 23:43:04 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Courscollectif generated by hbm2java
 */
@Entity
@Table(name = "courscollectif", catalog = "fitnessclub")
public class Courscollectif implements java.io.Serializable {

	private Integer idCours;
	private String nomCours;
	private String jourCours;
	private String heureCours;
	private String dureeCours;
	private int idPersonne;

	public Courscollectif() {
	}

	public Courscollectif(String nomCours, String jourCours, String heureCours,
			String dureeCours, int idPersonne) {
		this.nomCours = nomCours;
		this.jourCours = jourCours;
		this.heureCours = heureCours;
		this.dureeCours = dureeCours;
		this.idPersonne = idPersonne;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idCours", unique = true, nullable = false)
	public Integer getIdCours() {
		return this.idCours;
	}

	public void setIdCours(Integer idCours) {
		this.idCours = idCours;
	}

	@Column(name = "nomCours", nullable = false, length = 50)
	public String getNomCours() {
		return this.nomCours;
	}

	public void setNomCours(String nomCours) {
		this.nomCours = nomCours;
	}

	@Column(name = "jourCours", nullable = false, length = 10)
	public String getJourCours() {
		return this.jourCours;
	}

	public void setJourCours(String jourCours) {
		this.jourCours = jourCours;
	}

	@Column(name = "heureCours", nullable = false, length = 10)
	public String getHeureCours() {
		return this.heureCours;
	}

	public void setHeureCours(String heureCours) {
		this.heureCours = heureCours;
	}

	@Column(name = "dureeCours", nullable = false, length = 10)
	public String getDureeCours() {
		return this.dureeCours;
	}

	public void setDureeCours(String dureeCours) {
		this.dureeCours = dureeCours;
	}

	@Column(name = "idPersonne", nullable = false)
	public int getIdPersonne() {
		return this.idPersonne;
	}

	public void setIdPersonne(int idPersonne) {
		this.idPersonne = idPersonne;
	}

}
