package pojo;

// Generated 01-juin-2014 23:43:04 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DoitAvoir generated by hbm2java
 */
@Entity
@Table(name = "doit_avoir", catalog = "fitnessclub")
public class DoitAvoir implements java.io.Serializable {

	private DoitAvoirId id;

	public DoitAvoir() {
	}

	public DoitAvoir(DoitAvoirId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idContact", column = @Column(name = "idContact", nullable = false)),
			@AttributeOverride(name = "idPersonne", column = @Column(name = "idPersonne", nullable = false)) })
	public DoitAvoirId getId() {
		return this.id;
	}

	public void setId(DoitAvoirId id) {
		this.id = id;
	}

}
