package pojo;

// Generated 01-juin-2014 23:43:04 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Employe generated by hbm2java
 */
@Entity
@Table(name = "employe", catalog = "fitnessclub")
public class Employe implements java.io.Serializable {

	private int idPersonne;

	public Employe() {
	}

	public Employe(int idPersonne) {
		this.idPersonne = idPersonne;
	}

	@Id
	@Column(name = "idPersonne", unique = true, nullable = false)
	public int getIdPersonne() {
		return this.idPersonne;
	}

	public void setIdPersonne(int idPersonne) {
		this.idPersonne = idPersonne;
	}

}
