package pojo;

// Generated 01-juin-2014 23:43:04 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Engage generated by hbm2java
 */
@Entity
@Table(name = "engage", catalog = "fitnessclub")
public class Engage implements java.io.Serializable {

	private EngageId id;

	public Engage() {
	}

	public Engage(EngageId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idLicence", column = @Column(name = "idLicence", nullable = false)),
			@AttributeOverride(name = "idPersonne", column = @Column(name = "idPersonne", nullable = false)) })
	public EngageId getId() {
		return this.id;
	}

	public void setId(EngageId id) {
		this.id = id;
	}

}
