package pojo;

// Generated 01-juin-2014 23:43:04 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Fitnessclub generated by hbm2java
 */
@Entity
@Table(name = "fitnessclub", catalog = "fitnessclub")
public class Fitnessclub implements java.io.Serializable {

	private Integer idLicence;
	private String nomCompagnie;
	private String telephone;
	private String email;

	public Fitnessclub() {
	}

	public Fitnessclub(String nomCompagnie, String telephone, String email) {
		this.nomCompagnie = nomCompagnie;
		this.telephone = telephone;
		this.email = email;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idLicence", unique = true, nullable = false)
	public Integer getIdLicence() {
		return this.idLicence;
	}

	public void setIdLicence(Integer idLicence) {
		this.idLicence = idLicence;
	}

	@Column(name = "NomCompagnie", nullable = false, length = 20)
	public String getNomCompagnie() {
		return this.nomCompagnie;
	}

	public void setNomCompagnie(String nomCompagnie) {
		this.nomCompagnie = nomCompagnie;
	}

	@Column(name = "telephone", nullable = false, precision = 10, scale = 0)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "email", nullable = false, length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
