package pojo;

// Generated 01-juin-2014 23:43:04 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Lockers generated by hbm2java
 */
@Entity
@Table(name = "lockers", catalog = "fitnessclub", uniqueConstraints = @UniqueConstraint(columnNames = "idPersonne"))
public class Lockers implements java.io.Serializable {

	private Integer idLocker;
	private int idPersonne;
	private String section;
	private String loue;
	private BigDecimal prix;
	private int idLicence;

	public Lockers() {
	}

	public Lockers(int idPersonne, String section, String loue,
			BigDecimal prix, int idLicence) {
		this.idPersonne = idPersonne;
		this.section = section;
		this.loue = loue;
		this.prix = prix;
		this.idLicence = idLicence;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idLocker", unique = true, nullable = false)
	public Integer getIdLocker() {
		return this.idLocker;
	}

	public void setIdLocker(Integer idLocker) {
		this.idLocker = idLocker;
	}

	@Column(name = "idPersonne", unique = true, nullable = false)
	public int getIdPersonne() {
		return this.idPersonne;
	}

	public void setIdPersonne(int idPersonne) {
		this.idPersonne = idPersonne;
	}

	@Column(name = "section", nullable = false, length = 20)
	public String getSection() {
		return this.section;
	}

	public void setSection(String section) {
		this.section = section;
	}

	@Column(name = "loue", nullable = false, length = 3)
	public String getLoue() {
		return this.loue;
	}

	public void setLoue(String loue) {
		this.loue = loue;
	}

	@Column(name = "prix", nullable = false, precision = 20, scale = 0)
	public BigDecimal getPrix() {
		return this.prix;
	}

	public void setPrix(BigDecimal prix) {
		this.prix = prix;
	}

	@Column(name = "idLicence", nullable = false)
	public int getIdLicence() {
		return this.idLicence;
	}

	public void setIdLicence(int idLicence) {
		this.idLicence = idLicence;
	}

}
