package pojo;

// Generated 01-juin-2014 23:43:04 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VendId generated by hbm2java
 */
@Embeddable
public class VendId implements java.io.Serializable {

	private int idProduit;
	private int idLicence;

	public VendId() {
	}

	public VendId(int idProduit, int idLicence) {
		this.idProduit = idProduit;
		this.idLicence = idLicence;
	}

	@Column(name = "idProduit", nullable = false)
	public int getIdProduit() {
		return this.idProduit;
	}

	public void setIdProduit(int idProduit) {
		this.idProduit = idProduit;
	}

	@Column(name = "idLicence", nullable = false)
	public int getIdLicence() {
		return this.idLicence;
	}

	public void setIdLicence(int idLicence) {
		this.idLicence = idLicence;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VendId))
			return false;
		VendId castOther = (VendId) other;

		return (this.getIdProduit() == castOther.getIdProduit())
				&& (this.getIdLicence() == castOther.getIdLicence());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdProduit();
		result = 37 * result + this.getIdLicence();
		return result;
	}

}
