package pojo;

// Generated 01-juin-2014 23:43:04 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Vend generated by hbm2java
 */
@Entity
@Table(name = "vend", catalog = "fitnessclub")
public class Vend implements java.io.Serializable {

	private VendId id;

	public Vend() {
	}

	public Vend(VendId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idProduit", column = @Column(name = "idProduit", nullable = false)),
			@AttributeOverride(name = "idLicence", column = @Column(name = "idLicence", nullable = false)) })
	public VendId getId() {
		return this.id;
	}

	public void setId(VendId id) {
		this.id = id;
	}

}
